# no
COMBO_ENABLE = no
CONSOLE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = no
VIA_ENABLE = no
VIAL_ENABLE = no

# yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes
